<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Fresh Eggs Tray',
                'description' => 'Farm fresh eggs packed by tray.',
                'image' => 'https://images.unsplash.com/photo-1598965675036-6c3c7e3e6e6e?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'dozen',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 650,
            ],
            [
                'name' => 'Broiler Chicken',
                'description' => 'Live broiler chicken per piece.',
                'image' => 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80',
                'type' => 'livestock',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'piece',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 3500,
            ],
            [
                'name' => 'Starter Feed Bag',
                'description' => '25kg starter feed bag for chicks.',
                'image' => 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&q=80',
                'type' => 'feed',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bag',
                'pack_size' => 25,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 14500,
            ],
            [
                'name' => 'Hybrid Maize Seedlings',
                'description' => 'Pre-order hybrid maize seedlings.',
                'image' => 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&q=80',
                'type' => 'seedlings',
                'status' => Product::STATUS_DRAFT,
                'unit' => 'crate',
                'pack_size' => 50,
                'is_preorder' => true,
                'is_seasonal' => true,
                'requires_cold_chain' => false,
                'price' => 12000,
            ],
            [
                'name' => 'Organic Tomatoes',
                'description' => 'Fresh organic tomatoes from the farm.',
                'image' => 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'kg',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => true,
                'requires_cold_chain' => true,
                'price' => 800,
            ],
            [
                'name' => 'Fresh Milk',
                'description' => 'Raw fresh milk directly from dairy cows.',
                'image' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&q=80',
                'type' => 'dairy',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'liter',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 450,
            ],
            [
                'name' => 'Layer Feed',
                'description' => 'Premium layer feed for egg production.',
                'image' => 'https://images.unsplash.com/photo-1563205764-5d59957f5e9e?w=800&q=80',
                'type' => 'feed',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bag',
                'pack_size' => 50,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 22000,
            ],
            [
                'name' => 'Free Range Chicken',
                'description' => 'Free range chicken raised naturally.',
                'image' => 'https://images.unsplash.com/photo-1560706256-29d3a1d4a4f8?w=800&q=80',
                'type' => 'livestock',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'piece',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 4500,
            ],
            [
                'name' => 'Organic Lettuce',
                'description' => 'Crisp organic lettuce heads.',
                'image' => 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'head',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 350,
            ],
            [
                'name' => 'Farm Honey',
                'description' => 'Pure raw honey from farm beehives.',
                'image' => 'https://images.unsplash.com/photo-1587049352846-4a2438248e85?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'jar',
                'pack_size' => 500,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 2500,
            ],
            [
                'name' => 'Potato Sack',
                'description' => 'Fresh potatoes 10kg sack.',
                'image' => 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'sack',
                'pack_size' => 10,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 3200,
            ],
            [
                'name' => 'Duck Eggs',
                'description' => 'Fresh duck eggs dozen pack.',
                'image' => 'https://images.unsplash.com/photo-1596707328771-46161e7c9e75?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'dozen',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 900,
            ],
            [
                'name' => 'Corn Feed',
                'description' => 'Whole corn kernels for poultry feed.',
                'image' => 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&q=80',
                'type' => 'feed',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bag',
                'pack_size' => 50,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 11000,
            ],
            [
                'name' => 'Goat Kid',
                'description' => 'Young goat for breeding or meat.',
                'image' => 'https://images.unsplash.com/photo-1524024973431-1ad379f87a84?w=800&q=80',
                'type' => 'livestock',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'piece',
                'pack_size' => 1,
                'is_preorder' => true,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 15000,
            ],
            [
                'name' => 'Fresh Carrots',
                'description' => 'Organic carrots bunch.',
                'image' => 'https://images.unsplash.com/photo-1598170845058-32b9d6a5f375?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bunch',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 400,
            ],
            [
                'name' => 'Turkey',
                'description' => 'Live turkey for special occasions.',
                'image' => 'https://images.unsplash.com/photo-1544377288-3c599a05dc11?w=800&q=80',
                'type' => 'livestock',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'piece',
                'pack_size' => 1,
                'is_preorder' => true,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 25000,
            ],
            [
                'name' => 'Cabbage Head',
                'description' => 'Fresh green cabbage head.',
                'image' => 'https://images.unsplash.com/photo-1550441199-896e0e778e5a?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'head',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 500,
            ],
            [
                'name' => 'Quail Eggs',
                'description' => 'Premium quail eggs pack of 20.',
                'image' => 'https://images.unsplash.com/photo-1596707328771-46161e7c9e75?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'pack',
                'pack_size' => 20,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 1200,
            ],
            [
                'name' => 'Wheat Grains',
                'description' => 'Quality wheat grains for feed or milling.',
                'image' => 'https://images.unsplash.com/photo-1574323347407-f5e1ad6f020b?w=800&q=80',
                'type' => 'feed',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bag',
                'pack_size' => 50,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 18000,
            ],
            [
                'name' => 'Bell Peppers Mix',
                'description' => 'Mixed color bell peppers kg pack.',
                'image' => 'https://images.unsplash.com/photo-1563565375-f3fdf5d7e1e8?w=800&q=80',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'kg',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 1500,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['name' => $product['name']],
                $product
            );
        }
    }
}
