<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Fresh Eggs Tray',
                'description' => 'Farm fresh eggs packed by tray.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Chicken_eggs_in_tray.jpg',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'dozen',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 650,
            ],
            [
                'name' => 'Broiler Chicken',
                'description' => 'Live broiler chicken per piece.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Broiler_Chicken_at_a_farm.jpg',
                'type' => 'livestock',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'piece',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 3500,
            ],
            [
                'name' => 'Starter Feed Bag',
                'description' => '25kg starter feed bag for chicks.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Pellets.jpg',
                'type' => 'feed',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bag',
                'pack_size' => 25,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 14500,
            ],
            [
                'name' => 'Hybrid Maize Seedlings',
                'description' => 'Pre-order hybrid maize seedlings.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Maize_Seedlings_02.jpg',
                'type' => 'seedlings',
                'status' => Product::STATUS_DRAFT,
                'unit' => 'crate',
                'pack_size' => 50,
                'is_preorder' => true,
                'is_seasonal' => true,
                'requires_cold_chain' => false,
                'price' => 12000,
            ],
            [
                'name' => 'Organic Tomatoes',
                'description' => 'Fresh organic tomatoes from the farm.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Tomato_je.jpg',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'kg',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => true,
                'requires_cold_chain' => true,
                'price' => 800,
            ],
            [
                'name' => 'Fresh Milk',
                'description' => 'Raw fresh milk directly from dairy cows.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Glass_of_Milk_%2833657535532%29.jpg',
                'type' => 'dairy',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'liter',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 450,
            ],
            [
                'name' => 'Layer Feed',
                'description' => 'Premium layer feed for egg production.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Wheat_close-up.JPG',
                'type' => 'feed',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bag',
                'pack_size' => 50,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 22000,
            ],
            [
                'name' => 'Free Range Chicken',
                'description' => 'Free range chicken raised naturally.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Free_range_chicken.jpg',
                'type' => 'livestock',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'piece',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 4500,
            ],
            [
                'name' => 'Organic Lettuce',
                'description' => 'Crisp organic lettuce heads.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Lettuce.jpg',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'head',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 350,
            ],
            [
                'name' => 'Farm Honey',
                'description' => 'Pure raw honey from farm beehives.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Honey_%28Italian-miele%29_in_a_jar.jpg',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'jar',
                'pack_size' => 500,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 2500,
            ],
            [
                'name' => 'Potato Sack',
                'description' => 'Fresh potatoes 10kg sack.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Potato_tubers.jpg',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'sack',
                'pack_size' => 10,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 3200,
            ],
            [
                'name' => 'Duck Eggs',
                'description' => 'Fresh duck eggs dozen pack.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Duck_eggs.jpg',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'dozen',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 900,
            ],
            [
                'name' => 'Corn Feed',
                'description' => 'Whole corn kernels for poultry feed.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Corn_Kernels.jpg',
                'type' => 'feed',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bag',
                'pack_size' => 50,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 11000,
            ],
            [
                'name' => 'Goat Kid',
                'description' => 'Young goat for breeding or meat.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/A_young_goat%2C_or_%22kid%22.jpg',
                'type' => 'livestock',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'piece',
                'pack_size' => 1,
                'is_preorder' => true,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 15000,
            ],
            [
                'name' => 'Fresh Carrots',
                'description' => 'Organic carrots bunch.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Carrots.JPG',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bunch',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 400,
            ],
            [
                'name' => 'Turkey',
                'description' => 'Live turkey for special occasions.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Turkey_Tom.jpg',
                'type' => 'livestock',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'piece',
                'pack_size' => 1,
                'is_preorder' => true,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 25000,
            ],
            [
                'name' => 'Cabbage Head',
                'description' => 'Fresh green cabbage head.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Freshly_picked_Cabbage_head_02.jpg',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'head',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 500,
            ],
            [
                'name' => 'Quail Eggs',
                'description' => 'Premium quail eggs pack of 20.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Quail_Eggs.jpg',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'pack',
                'pack_size' => 20,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 1200,
            ],
            [
                'name' => 'Wheat Grains',
                'description' => 'Quality wheat grains for feed or milling.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Wheat_grains.JPG',
                'type' => 'feed',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'bag',
                'pack_size' => 50,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => false,
                'price' => 18000,
            ],
            [
                'name' => 'Bell Peppers Mix',
                'description' => 'Mixed color bell peppers kg pack.',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Bell_Peppers.jpg',
                'type' => 'produce',
                'status' => Product::STATUS_PUBLISHED,
                'unit' => 'kg',
                'pack_size' => 1,
                'is_preorder' => false,
                'is_seasonal' => false,
                'requires_cold_chain' => true,
                'price' => 1500,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['name' => $product['name']],
                $product
            );
        }
    }
}
